dependencies:
  flutter:
    sdk: flutter
  
  # Core Logic
  provider: ^6.0.0
  equatable: ^2.0.5
  
  # Networking (MySQL/API)
  http: ^1.1.0
  
  # Local Database (Offline)
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utils
  shared_preferences: ^2.2.0 (Untuk simpan sesi login)
