dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Koneksi Internet (ke MySQL)
  http: ^1.2.0
  
  # Database Lokal (Offline)
  sqflite: ^2.3.2
  path: ^1.9.0
  
  # Utilitas
  equatable: ^2.0.5
